'use strict';

const RESOURCE_CONFIG = {
  'news': {
    uid: 'api::news.news',
    label: 'Tin tức',
    pluralLabel: 'Tin tức',
    draftAndPublish: true,
    titleField: 'title',
    defaultSort: { date: 'desc' },
    searchableFields: ['title', 'summary', 'category'],
    editableFields: ['title', 'slug', 'summary', 'content', 'category', 'date', 'image'],
    listFields: ['title', 'category', 'date', 'publishedAt'],
    fields: {
      title: { label: 'Tiêu đề', type: 'text', required: true, maxLength: 300 },
      slug: { label: 'Đường dẫn', type: 'slug', required: true, from: 'title' },
      summary: { label: 'Tóm tắt', type: 'textarea', required: true, maxLength: 500 },
      content: { label: 'Nội dung', type: 'richtext', required: true },
      category: {
        label: 'Danh mục',
        type: 'select',
        required: true,
        options: [
          { value: 'gia-ca', label: 'Giá cả' },
          { value: 'quoc-te', label: 'Quốc tế' },
          { value: 'noi-dia', label: 'Nội địa' },
          { value: 'phan-tich', label: 'Phân tích' },
          { value: 'cong-nghe', label: 'Công nghệ' },
        ],
      },
      date: { label: 'Ngày đăng', type: 'date', required: true },
      image: { label: 'Ảnh đại diện', type: 'cloudinary-image', folder: 'ha-can/news' },
    },
  },
  'products': {
    uid: 'api::product.product',
    label: 'Sản phẩm',
    pluralLabel: 'Sản phẩm',
    draftAndPublish: false,
    titleField: 'name',
    defaultSort: { sort_order: 'asc' },
    searchableFields: ['name', 'uid', 'grade', 'origin'],
    editableFields: ['uid', 'name', 'group', 'grade', 'origin', 'price', 'description', 'specs', 'image', 'featured', 'in_stock', 'sort_order'],
    listFields: ['name', 'group', 'price', 'featured', 'in_stock'],
    fields: {
      uid: { label: 'Mã/đường dẫn', type: 'slug', required: true, from: 'name' },
      name: { label: 'Tên sản phẩm', type: 'text', required: true, maxLength: 200 },
      group: {
        label: 'Nhóm',
        type: 'select',
        required: true,
        options: [
          { value: 'dong', label: 'Đồng' },
          { value: 'nhom', label: 'Nhôm' },
          { value: 'chi', label: 'Chì' },
          { value: 'thiec', label: 'Thiếc' },
          { value: 'quang', label: 'Quặng' },
        ],
      },
      grade: { label: 'Hàm lượng/grade', type: 'text', maxLength: 100 },
      origin: { label: 'Nguồn gốc', type: 'text', maxLength: 200 },
      price: { label: 'Giá', type: 'number', min: 0 },
      description: { label: 'Mô tả', type: 'textarea', maxLength: 5000 },
      specs: { label: 'Thông số', type: 'key-value-table' },
      image: { label: 'Ảnh sản phẩm', type: 'cloudinary-image', folder: 'ha-can/products' },
      featured: { label: 'Nổi bật', type: 'boolean' },
      in_stock: { label: 'Còn hàng', type: 'boolean' },
      sort_order: { label: 'Thứ tự', type: 'number', default: 0 },
    },
  },
  'projects': {
    uid: 'api::project.project',
    label: 'Dự án',
    pluralLabel: 'Dự án',
    draftAndPublish: true,
    titleField: 'name',
    defaultSort: { createdAt: 'desc' },
    searchableFields: ['name', 'location', 'method'],
    editableFields: ['name', 'location', 'scale', 'method', 'value', 'image'],
    listFields: ['name', 'location', 'method', 'publishedAt'],
    fields: {
      name: { label: 'Tên dự án', type: 'text', required: true, maxLength: 300 },
      location: { label: 'Địa điểm', type: 'text', required: true, maxLength: 300 },
      scale: { label: 'Quy mô', type: 'text', maxLength: 200 },
      method: { label: 'Phương pháp', type: 'text', maxLength: 200 },
      value: { label: 'Giá trị', type: 'text', maxLength: 200 },
      image: { label: 'Ảnh dự án', type: 'cloudinary-image', folder: 'ha-can/projects' },
    },
  },
  'services': {
    uid: 'api::service.service',
    label: 'Dịch vụ',
    pluralLabel: 'Dịch vụ',
    draftAndPublish: true,
    titleField: 'title',
    defaultSort: { sort_order: 'asc' },
    searchableFields: ['title', 'description'],
    editableFields: ['title', 'description', 'features', 'icon_svg', 'link_url', 'link_text', 'sort_order'],
    listFields: ['title', 'link_text', 'sort_order', 'publishedAt'],
    fields: {
      title: { label: 'Tiêu đề', type: 'text', required: true, maxLength: 200 },
      description: { label: 'Mô tả', type: 'textarea', required: true, maxLength: 1000 },
      features: { label: 'Tính năng', type: 'text-list' },
      icon_svg: { label: 'Icon SVG', type: 'code', maxLength: 2000 },
      link_url: { label: 'Liên kết', type: 'text', maxLength: 500 },
      link_text: { label: 'Chữ trên nút', type: 'text', maxLength: 100 },
      sort_order: { label: 'Thứ tự', type: 'number', default: 0 },
    },
  },
  'hero-slides': {
    uid: 'api::hero-slide.hero-slide',
    label: 'Slide trang chủ',
    pluralLabel: 'Slide trang chủ',
    draftAndPublish: true,
    titleField: 'title',
    defaultSort: { sort_order: 'asc' },
    searchableFields: ['title', 'subtitle'],
    editableFields: ['subtitle', 'title', 'image_url', 'image_alt', 'sort_order'],
    listFields: ['title', 'subtitle', 'sort_order', 'publishedAt'],
    fields: {
      subtitle: { label: 'Dòng phụ', type: 'text', required: true, maxLength: 200 },
      title: { label: 'Tiêu đề', type: 'text', required: true, maxLength: 200 },
      image_url: { label: 'Ảnh slide', type: 'cloudinary-image', required: true, folder: 'ha-can/hero' },
      image_alt: { label: 'Mô tả ảnh', type: 'textarea', maxLength: 500 },
      sort_order: { label: 'Thứ tự', type: 'number', default: 0 },
    },
  },
  'workflow-steps': {
    uid: 'api::workflow-step.workflow-step',
    label: 'Bước quy trình',
    pluralLabel: 'Bước quy trình',
    draftAndPublish: true,
    titleField: 'title',
    defaultSort: { sort_order: 'asc' },
    searchableFields: ['title', 'description'],
    editableFields: ['step_number', 'title', 'description', 'sort_order'],
    listFields: ['step_number', 'title', 'sort_order', 'publishedAt'],
    fields: {
      step_number: { label: 'Số bước', type: 'number', required: true },
      title: { label: 'Tiêu đề', type: 'text', required: true, maxLength: 200 },
      description: { label: 'Mô tả', type: 'textarea', required: true, maxLength: 1000 },
      sort_order: { label: 'Thứ tự', type: 'number', default: 0 },
    },
  },
  'pricing-packages': {
    uid: 'api::pricing-package.pricing-package',
    label: 'Giá kim loại',
    pluralLabel: 'Giá kim loại',
    draftAndPublish: false,
    titleField: 'metal',
    defaultSort: { updated: 'desc' },
    searchableFields: ['metal', 'lme_price', 'domestic_price'],
    editableFields: ['metal', 'lme_price', 'domestic_price', 'unit', 'change', 'trend', 'updated'],
    listFields: ['metal', 'lme_price', 'domestic_price', 'trend', 'updated'],
    fields: {
      metal: { label: 'Kim loại', type: 'text', required: true, maxLength: 100 },
      lme_price: { label: 'Giá LME', type: 'text', maxLength: 50 },
      domestic_price: { label: 'Giá nội địa', type: 'text', maxLength: 50 },
      unit: { label: 'Đơn vị', type: 'text', maxLength: 20, default: '/kg' },
      change: { label: 'Thay đổi', type: 'text', maxLength: 20 },
      trend: {
        label: 'Xu hướng',
        type: 'select',
        options: [
          { value: 'up', label: 'Tăng' },
          { value: 'down', label: 'Giảm' },
          { value: 'stable', label: 'Ổn định' },
        ],
      },
      updated: { label: 'Ngày cập nhật', type: 'date' },
    },
  },
  'pricing-analyses': {
    uid: 'api::pricing-analysis.pricing-analysis',
    label: 'Biểu phí phân tích',
    pluralLabel: 'Biểu phí phân tích',
    draftAndPublish: true,
    titleField: 'name',
    defaultSort: { name: 'asc' },
    searchableFields: ['name', 'tech', 'category'],
    editableFields: ['name', 'tech', 'unit', 'price', 'duration', 'category'],
    listFields: ['name', 'tech', 'unit', 'price', 'publishedAt'],
    fields: {
      name: { label: 'Tên hạng mục', type: 'text', required: true, maxLength: 200 },
      tech: { label: 'Kỹ thuật', type: 'text', maxLength: 200 },
      unit: { label: 'Đơn vị', type: 'text', maxLength: 50, default: 'Mẫu' },
      price: { label: 'Giá', type: 'number', required: true, min: 0 },
      duration: { label: 'Thời gian', type: 'text', maxLength: 100 },
      category: {
        label: 'Nhóm',
        type: 'select',
        required: true,
        options: [
          { value: 'chemical', label: 'Hóa học' },
          { value: 'physical', label: 'Vật lý' },
        ],
      },
    },
  },
  'pricing-surveys': {
    uid: 'api::pricing-survey.pricing-survey',
    label: 'Biểu phí khảo sát',
    pluralLabel: 'Biểu phí khảo sát',
    draftAndPublish: true,
    titleField: 'name',
    defaultSort: { name: 'asc' },
    searchableFields: ['name', 'description'],
    editableFields: ['name', 'price', 'description'],
    listFields: ['name', 'price', 'publishedAt'],
    fields: {
      name: { label: 'Tên dịch vụ', type: 'text', required: true, maxLength: 200 },
      price: { label: 'Giá', type: 'text', required: true, maxLength: 100 },
      description: { label: 'Mô tả', type: 'textarea', maxLength: 2000 },
    },
  },
  'site-setting': {
    uid: 'api::site-setting.site-setting',
    label: 'Cài đặt website',
    pluralLabel: 'Cài đặt website',
    singleType: true,
    draftAndPublish: false,
    titleField: 'office_name',
    editableFields: [
      'hotline',
      'hotline2',
      'email',
      'address',
      'office_name',
      'tax_code',
      'facebook_url',
      'youtube_url',
      'zalo_url',
      'twitter_url',
      'hero_tagline',
      'hero_title',
      'hero_description',
      'hero_cert_label',
      'hero_cert_value',
      'brand_bio',
      'stat1_number',
      'stat1_label',
      'stat2_number',
      'stat2_label',
      'stat3_number',
      'stat3_label',
    ],
    listFields: ['office_name', 'hotline', 'email'],
    fields: {
      hotline: { label: 'Hotline', type: 'text', required: true, maxLength: 20 },
      hotline2: { label: 'Hotline phụ', type: 'text', maxLength: 20 },
      email: { label: 'Email', type: 'email', required: true, maxLength: 254 },
      address: { label: 'Địa chỉ', type: 'textarea', required: true, maxLength: 500 },
      office_name: { label: 'Tên văn phòng', type: 'text', maxLength: 200 },
      tax_code: { label: 'Mã số thuế', type: 'text', maxLength: 20 },
      facebook_url: { label: 'Facebook', type: 'url', maxLength: 500 },
      youtube_url: { label: 'YouTube', type: 'url', maxLength: 500 },
      zalo_url: { label: 'Zalo', type: 'url', maxLength: 500 },
      twitter_url: { label: 'Twitter/X', type: 'url', maxLength: 500 },
      hero_tagline: { label: 'Dòng giới thiệu trang chủ', type: 'text', maxLength: 200 },
      hero_title: { label: 'Tiêu đề trang chủ', type: 'text', maxLength: 200 },
      hero_description: { label: 'Mô tả trang chủ', type: 'textarea', maxLength: 1000 },
      hero_cert_label: { label: 'Nhãn chứng chỉ', type: 'text', maxLength: 50 },
      hero_cert_value: { label: 'Giá trị chứng chỉ', type: 'text', maxLength: 100 },
      brand_bio: { label: 'Giới thiệu thương hiệu', type: 'textarea', maxLength: 1000 },
      stat1_number: { label: 'Số liệu 1', type: 'text', maxLength: 20 },
      stat1_label: { label: 'Nhãn số liệu 1', type: 'text', maxLength: 100 },
      stat2_number: { label: 'Số liệu 2', type: 'text', maxLength: 20 },
      stat2_label: { label: 'Nhãn số liệu 2', type: 'text', maxLength: 100 },
      stat3_number: { label: 'Số liệu 3', type: 'text', maxLength: 20 },
      stat3_label: { label: 'Nhãn số liệu 3', type: 'text', maxLength: 100 },
    },
  },
  'contact-inquiries': {
    uid: 'api::contact-inquiry.contact-inquiry',
    label: 'Yêu cầu liên hệ',
    pluralLabel: 'Yêu cầu liên hệ',
    draftAndPublish: false,
    readOnlyCreate: true,
    titleField: 'name',
    defaultSort: { createdAt: 'desc' },
    searchableFields: ['name', 'phone', 'email', 'address', 'message'],
    editableFields: ['status'],
    listFields: ['name', 'phone', 'service', 'status', 'createdAt'],
    fields: {
      status: {
        label: 'Trạng thái',
        type: 'select',
        options: [
          { value: 'new', label: 'Mới' },
          { value: 'contacted', label: 'Đã liên hệ' },
          { value: 'completed', label: 'Hoàn tất' },
        ],
      },
    },
  },
  'order-requests': {
    uid: 'api::order-request.order-request',
    label: 'Đơn đặt mẫu',
    pluralLabel: 'Đơn đặt mẫu',
    draftAndPublish: false,
    readOnlyCreate: true,
    titleField: 'customer_name',
    defaultSort: { createdAt: 'desc' },
    searchableFields: ['product_name', 'customer_name', 'phone', 'email', 'note'],
    editableFields: ['status'],
    listFields: ['product_name', 'customer_name', 'phone', 'quantity', 'status', 'createdAt'],
    fields: {
      status: {
        label: 'Trạng thái',
        type: 'select',
        options: [
          { value: 'new', label: 'Mới' },
          { value: 'processing', label: 'Đang xử lý' },
          { value: 'done', label: 'Hoàn tất' },
        ],
      },
    },
  },
};

function getResourceConfig(type) {
  if (!Object.prototype.hasOwnProperty.call(RESOURCE_CONFIG, type)) {
    return null;
  }

  return RESOURCE_CONFIG[type];
}

function listResourceConfigs() {
  return Object.entries(RESOURCE_CONFIG).map(([type, config]) => ({ type, ...config }));
}

function isDraftEnabled(type) {
  const config = getResourceConfig(type);
  return Boolean(config && config.draftAndPublish);
}

module.exports = {
  RESOURCE_CONFIG,
  getResourceConfig,
  listResourceConfigs,
  isDraftEnabled,
};
